CREATE DATABASE notice_board;
USE notice_board;

DROP TABLE NTC01;
CREATE TABLE NTC01 (
    C01F01 INT PRIMARY KEY AUTO_INCREMENT COMMENT 'notice_id',
    C01F02 VARCHAR(30) NOT NULL COMMENT 'title',
    C01F03 VARCHAR(100) COMMENT 'description',
    C01F04 DATETIME NOT NULL COMMENT 'notice_date'
);

INSERT INTO NTC01 VALUES (0,"Test","This is test notice",NOW());
SELECT * FROM NTC01;