CREATE DATABASE e_commerce_platform;
USE e_commerce_platform;

DROP TABLE CTG01;
CREATE TABLE CTG01 (
    G01F01 INT PRIMARY KEY COMMENT 'category_id',
    G01F02 VARCHAR(30) NOT NULL UNIQUE COMMENT 'name',
    G01F03 VARCHAR(50) COMMENT 'description'
);

INSERT INTO CTG01 VALUES(1,'stationary','stationary for student');

DROP TABLE PRD01;
CREATE TABLE PRD01 (
    D01F01 INT PRIMARY KEY COMMENT 'product_id',
    D01F02 VARCHAR(30) NOT NULL UNIQUE COMMENT 'product_name',
    D01F03 INT NOT NULL COMMENT 'quantity',
    D01F04 INT NOT NULL COMMENT 'price',
    D01F05 INT NOT NULL COMMENT 'category_id',
    FOREIGN KEY (D01F05)
        REFERENCES CTG01 (G01F01)
);

DROP TABLE ORD01;
CREATE TABLE ORD01 (
    D01F01 INT PRIMARY KEY AUTO_INCREMENT COMMENT 'order_id',
    D01F02 INT NOT NULL COMMENT 'product_id',
    D01F03 INT NOT NULL COMMENT 'quantity',
    D01F04 INT NOT NULL COMMENT 'total_amount',
    D01F05 ENUM('pending', 'success') NOT NULL DEFAULT 'pending' COMMENT 'order_status',
    D01F06 DATETIME NOT NULL COMMENT 'order_date',
    FOREIGN KEY (D01F02)
        REFERENCES PRD01 (D01F01)
);
